//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarathonSystem.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MarathonSystem.Properties.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These credentials do not match our records..
        /// </summary>
        internal static string auth_failed {
            get {
                return ResourceManager.GetString("auth_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong password. Please try again..
        /// </summary>
        internal static string auth_password {
            get {
                return ResourceManager.GetString("auth_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized Action.
        /// </summary>
        internal static string auth_unauth {
            get {
                return ResourceManager.GetString("auth_unauth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown requirement..
        /// </summary>
        internal static string auth_unknownreq {
            get {
                return ResourceManager.GetString("auth_unknownreq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot assign a new checkpoint before you apply the existed one..
        /// </summary>
        internal static string checkpoint_unavaliable {
            get {
                return ResourceManager.GetString("checkpoint_unavaliable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This method required authentication..
        /// </summary>
        internal static string payment_auth {
            get {
                return ResourceManager.GetString("payment_auth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service is unavailable. Please try again later..
        /// </summary>
        internal static string service_unavailable {
            get {
                return ResourceManager.GetString("service_unavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must be 18 years old or above to use this function..
        /// </summary>
        internal static string validation_adult {
            get {
                return ResourceManager.GetString("validation_adult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter all the required fields..
        /// </summary>
        internal static string validation_allrequired {
            get {
                return ResourceManager.GetString("validation_allrequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords must be at least six characters, one uppercase characters, one special charaters and match the confirmation.
        /// </summary>
        internal static string validation_confirmed {
            get {
                return ResourceManager.GetString("validation_confirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} is not a valid date..
        /// </summary>
        internal static string validation_date {
            get {
                return ResourceManager.GetString("validation_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be a valid email address..
        /// </summary>
        internal static string validation_email {
            get {
                return ResourceManager.GetString("validation_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected {0} is invalid..
        /// </summary>
        internal static string validation_exists {
            get {
                return ResourceManager.GetString("validation_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The gender is invalid..
        /// </summary>
        internal static string validation_gender {
            get {
                return ResourceManager.GetString("validation_gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} may not be greater than {1}..
        /// </summary>
        internal static string validation_max {
            get {
                return ResourceManager.GetString("validation_max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be at least {1} characters..
        /// </summary>
        internal static string validation_min {
            get {
                return ResourceManager.GetString("validation_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords must be at least six characters, one uppercase characters, one special charaters and match the confirmation.
        /// </summary>
        internal static string validation_password {
            get {
                return ResourceManager.GetString("validation_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field must be present..
        /// </summary>
        internal static string validation_present {
            get {
                return ResourceManager.GetString("validation_present", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field is required..
        /// </summary>
        internal static string validation_required {
            get {
                return ResourceManager.GetString("validation_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} has already been taken..
        /// </summary>
        internal static string validation_unique {
            get {
                return ResourceManager.GetString("validation_unique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit exceeded. Please try again after 15 minutes..
        /// </summary>
        internal static string verification_limit {
            get {
                return ResourceManager.GetString("verification_limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Token..
        /// </summary>
        internal static string verification_token {
            get {
                return ResourceManager.GetString("verification_token", resourceCulture);
            }
        }
    }
}
