//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarathonSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarathonEvent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MarathonEvent()
        {
            this.Registrations = new HashSet<Registration>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public int type_id { get; set; }
        public int quota { get; set; }
        public int start_at { get; set; }
        public int end_at { get; set; }
        public int created_at { get; set; }
        public int updated_at { get; set; }
        public Nullable<decimal> cost { get; set; }
        public int marathon_id { get; set; }
        public int start_datetime { get; set; }
        public int state { get; set; }
        public int currentQuota { get; set; }
    
        public virtual EventType EventType { get; set; }
        public virtual Marathon Marathon { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Registration> Registrations { get; set; }
    }
}
