//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarathonSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MarathonEntities : DbContext
    {
        public MarathonEntities()
            : base("name=MarathonEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BankReceipt> BankReceipts { get; set; }
        public virtual DbSet<Banner> Banners { get; set; }
        public virtual DbSet<Charity> Charities { get; set; }
        public virtual DbSet<Checkpoint> Checkpoints { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<EventType> EventTypes { get; set; }
        public virtual DbSet<Feedback> Feedbacks { get; set; }
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<Marathon> Marathons { get; set; }
        public virtual DbSet<MarathonEvent> MarathonEvents { get; set; }
        public virtual DbSet<Member> Members { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<Photo> Photos { get; set; }
        public virtual DbSet<RaceKit> RaceKits { get; set; }
        public virtual DbSet<Registration> Registrations { get; set; }
        public virtual DbSet<RunnerEvent> RunnerEvents { get; set; }
        public virtual DbSet<Service> Services { get; set; }
        public virtual DbSet<Sponsorship> Sponsorships { get; set; }
        public virtual DbSet<StatLog> StatLogs { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<Verification> Verifications { get; set; }
    }
}
