//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarathonSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registration
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Registration()
        {
            this.RunnerEvents = new HashSet<RunnerEvent>();
        }
    
        public int id { get; set; }
        public int user_id { get; set; }
        public decimal cost { get; set; }
        public int created_at { get; set; }
        public int updated_at { get; set; }
        public int racekit_id { get; set; }
        public int charity_id { get; set; }
        public decimal sponsorship { get; set; }
        public int event_id { get; set; }
        public int approval { get; set; }
        public Nullable<int> bank_id { get; set; }
    
        public virtual BankReceipt BankReceipt { get; set; }
        public virtual Charity Charity { get; set; }
        public virtual MarathonEvent MarathonEvent { get; set; }
        public virtual Member Member { get; set; }
        public virtual RaceKit RaceKit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RunnerEvent> RunnerEvents { get; set; }
    }
}
