//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarathonSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RunnerEvent
    {
        public int id { get; set; }
        public int registration_id { get; set; }
        public int finished_at { get; set; }
        public int created_at { get; set; }
        public int updated_at { get; set; }
        public int bib_id { get; set; }
        public Nullable<int> volunteer_id { get; set; }
        public int racekitsend { get; set; }
        public int checkin_at { get; set; }
    
        public virtual Member Member { get; set; }
        public virtual Registration Registration { get; set; }
    }
}
