//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarathonSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sponsorship
    {
        public int id { get; set; }
        public string name { get; set; }
        public int runner_id { get; set; }
        public Nullable<decimal> amount { get; set; }
        public int created_at { get; set; }
        public int updated_at { get; set; }
    
        public virtual Member Member { get; set; }
    }
}
